#include "hal_data.h"
#include "loader_table.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event)
BSP_PLACE_IN_SECTION(".warm_start");
FSP_CPP_FOOTER

extern bsp_leds_t g_bsp_leds;
extern void bsp_copy_multibyte(uintptr_t * src, uintptr_t * dst, uintptr_t bytesize);
extern void loader_external_memory_init(void);

/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    uint32_t table_num;

    void (*app_prg)(void);
    const loader_table * table;

    if (!loader_table_init())
    {
        while (1)
        {
            ;
        }
    }

    table = loader_table_get();

    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* If this board has no LEDs then trap here */
    if (0 == leds.led_count)
    {
        while (1)
        {
            ;                          // There are no LEDs on this board
        }
    }

    /* Holds level to set for pins */
    bsp_io_level_t pin_level = BSP_IO_LEVEL_HIGH;

    /* Unprotect I/O port registers */
    R_BSP_PinAccessEnable();

    /* Turn on LED0: Indicate application program copy start */
    pin_level = R_BSP_PortRead(BSP_IO_REGION_SAFE, BSP_IO_PORT_18);
    R_BSP_PortWrite(BSP_IO_REGION_SAFE, BSP_IO_PORT_18, (pin_level | 1U << 2));

    /* Copy application program with parameter in loader table. */
    /* The generic image manifest supplies the section copy table. */
    for ( table_num = 0; table_num < TABLE_ENTRY_NUM; table_num++)
    {
        if (table[table_num].enable_flag == TABLE_ENABLE)
        {
            bsp_copy_multibyte(table[table_num].src, table[table_num].dst, table[table_num].size);
        }
    }

    /* Ensuring data-changing */
    __asm volatile("dsb");

    /* Turn on LED3: Indicate application program copy end */
    pin_level = R_BSP_PortRead(BSP_IO_REGION_SAFE, BSP_IO_PORT_17);
    R_BSP_PortWrite(BSP_IO_REGION_SAFE, BSP_IO_PORT_17, (pin_level | 1U << 3));

    /* Protect I/O port registers */
    R_BSP_PinAccessDisable();

    /* Delay */
    R_BSP_SoftwareDelay(1000, BSP_DELAY_UNITS_MILLISECONDS);

    /* Set application program destination to app_prg */
    app_prg = (void (*)(void)) loader_application_entry();

    /* Jump to the application project */
    app_prg();
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
#define QSPI_CMD_WRITE_ENABLE 0
#define QSPI_CMD_WRITE_STATUS 1
#define QSPI_CMD_READ_STATUS  2
spi_flash_direct_transfer_t qspi_command[3] =
{
    {
    .command        = 0x06, // WEN(Write Enable)
    .address        = 0U,
    .data           = 0U,
    .command_length = 1U,
    .address_length = 0U,
    .data_length    = 0U,
    .dummy_cycles   = 0U
    },
    {
    .command        = 0x01, // WRSR(Write Status Register)
    .address        = 0U,
    .data           = 0x40,
    .command_length = 1U,
    .address_length = 0U,
    .data_length    = 1U,
    .dummy_cycles   = 0U
    },
    {
    .command        = 0x05, // RDSR(Read Status Register)
    .address        = 0U,
    .data           = 0U,
    .command_length = 1U,
    .address_length = 0U,
    .data_length    = 1U,
    .dummy_cycles   = 0U
    },
};

void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
        /* Pre clock initialization */
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

#if BSP_FEATURE_DDR_SUPPORTED
  #if (1 == BSP_CFG_DDR_INIT_ENABLE)

       /* Initialize the DDR settings. */
       bsp_ddr_init();
 #endif
#endif

        if (NULL != g_bsp_pin_cfg.p_extend)
        {
            /* Configure pins. */
            R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
        }

        /* Keep the original project's xSPI Flash interface active for the
         * embedded application image, then initialize the selected external
         * SDRAM or HyperRAM implementation. */
        R_XSPI_QSPI_Open(&g_qspi_ldr_ctrl, &g_qspi_ldr_cfg);
        R_XSPI_QSPI_SpiProtocolSet(&g_qspi_ldr_ctrl, SPI_FLASH_PROTOCOL_1S_1S_1S);
        R_XSPI_QSPI_DirectTransfer(&g_qspi_ldr_ctrl, &qspi_command[QSPI_CMD_WRITE_ENABLE], SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
        R_XSPI_QSPI_DirectTransfer(&g_qspi_ldr_ctrl, &qspi_command[QSPI_CMD_WRITE_STATUS], SPI_FLASH_DIRECT_TRANSFER_DIR_WRITE);
        do{
            R_XSPI_QSPI_DirectTransfer(&g_qspi_ldr_ctrl, &qspi_command[QSPI_CMD_READ_STATUS], SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
        }while((qspi_command[QSPI_CMD_READ_STATUS].data & 0x01) == 0x0);
        do{
            R_XSPI_QSPI_DirectTransfer(&g_qspi_ldr_ctrl, &qspi_command[QSPI_CMD_READ_STATUS], SPI_FLASH_DIRECT_TRANSFER_DIR_READ);
        }while((qspi_command[QSPI_CMD_READ_STATUS].data & 0x41) != 0x40);
			R_XSPI_QSPI_SpiProtocolSet(&g_qspi_ldr_ctrl, SPI_FLASH_PROTOCOL_1S_4S_4S);
        loader_external_memory_init();
    }
}
